= DOCUMENTACIÓN GENERICA
---

Este es un proyecto basado en Antora que nos permite ir documentando toda la teoria que vamos viendo en los distintos proyectos y materias.

Lo que tenemos que entender de Antora principalmente es como funciona a la hora de incorporar documentación de otros proyectos.

==*antora-playbook.yml*

[source,yml]
----
site:
  title: Documentación teórica
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.gitlab.io/demo/docs-site
  start_page: main-documentation::index.adoc
content:
  sources:
  - url: https://github.com/xswt/NodeJS.git
    branches: [main]
    start_path: docs
  - url: https://github.com/xswt/Documentacion.git
    branches: [main]
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: ./prueba2.zip
    snapshot: true
runtime:
  fetch: true
----

Este es el fichero en el que vamos a tener *TODO* configurado. Para entenderlo mejor vamos a ir parte por parte explicandolo. 
[source,yml]
----
site:
  title: Documentación teórica
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.gitlab.io/demo/docs-site
  start_page: main-documentation::index.adoc
----

Toda esta parte corresponde a información del sitio en si pasando por el titulo y por la URL publica en la que podemos visualizarlo.

> Lo mas importante con diferencia seria la parte del *start_page* que nos va a indicar el fichero *HOME* que se lee nada mas abrir la pagina. 

Para saber de donde sale este fichero tendremos que ir en este mismo proyecto a la carpeta *./docs* dentro de esta tendremos un *.yml*

===*antora.yml*
[source,yml]
----
name: main-documentation
title: Antora Home Doc
version: 1.00
# prerelease: -
nav:
- modules/ROOT/nav.adoc
----

En estas lineas especificamos una *doc* o documentación con varios parametros como el titulo o la version. El que mas nos importa de estos
es el *name* ya que es el que identifica toda la documentación. 

[source,yml]
----
start_page: main-documentation::index.adoc
----

Volviendo a este linea de código y despues de haber explicado el *./doc* entendemos que le estamos indicando que el home page tiene que ser el index.adoc de la doc correspondiente al *name:main-documentation*


[source,yml]
----
content:
  sources:
  - url: https://github.com/xswt/NodeJS.git
    branches: [main]
    start_path: docs
  - url: https://github.com/xswt/Documentacion.git
    branches: [main]
    start_path: docs
----

*CONTENT* este apartado es de los mas importantes y es donde vamos a definir toda la documentación externa que nutre nuestro proyecto. Tenemos que indicar la ruta de git correspondiente, las ramas que queremos informar y el *path* donde arranca la doc.


[source,yml]
----
ui:
  bundle:
    url: ./prueba2.zip
    snapshot: true
----

*UI* nos permite especificar todo lo referente a estilos y *theme* sobre el que se muestra toda la doc informada.
El bundle seria un zip con todos los estilos correspondientes.


[source,yml]
----
runtime:
  fetch: true
----

Por ultimo el runtime nos permite especificar el fetch que se encarga de revisar posibles actualizaciones de todos los repos que informan algo de documentación.

== ¿Que estructura debe tener un ./docs?
Como hemos visto la documentación general se nutre de otros repos de git que tengan la base de *Antora* (COMPLETAR CON DOCUMENTACION DE NODEJS ToDo)
